server:
  port: 8080

spring:
    datasource:
        name: orcl
        url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
        username: Spring
        password: Spring
        driver-class-name: oracle.jdbc.driver.OracleDriver

mybatis:
    mapper-locations: classpath*:com/ycl/springdemo/**/dao/mapper/*.xml

